### ISSUE TITLE
SP menu unavailable on IOS

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#100]
The main SP menu is hidden by the header on IOS systems. This makes it impossible to use - no commands available.
![image1](https://cloud.githubusercontent.com/assets/6656350/8713318/9f64b03e-2baa-11e5-968d-68d5a1c7ed33.PNG)

**Comment by adam-collins** [comment]
on dev

**Comment by Tasilee** [comment]
Looks good! ToProd (asap)
