### ISSUE TITLE
Download object as shape file web service is broken

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/spatial-portal#101]
To reproduce:

Download a MERIT site created from the Northern Tablelands object from the NRM? layer using the web service:
http://spatial.ala.org.au/ws/shape/shp/6239192
This produces a shape file with a correct attribute table but no geometry.
Downloading the same object as WKT or geojson works correctly.

For reference, it works correctly via the UI:
View Northern Tablelands in spatial portal: http://spatial.ala.org.au/webportal//?pid=6239192
Download as shapefile using the user interface ("Quick links"->"Export area "...).  
This works as expected.

**Comment by adam-collins** [comment]
Fix is on spatial-dev for testing, http://spatial-dev.ala.org.au/ws/shape/shp/6314680

**Comment by Tasilee** [comment]
The fix example worked, but a duplicate layer is created as it cycles through two imports of the same shapefile in one import. Chrisala's didn't work so presume invalid shapefile generated.

**Comment by adam-collins** [comment]
The layers-service issue for /shape/shp/ is fixed.
