### ISSUE TITLE
Can't upload a shape file zipped with a container folder

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/spatial-portal#102]
It is not clear to me whether this is a user error, in which case a better error message would be helpful or it's allowed by the shape file standard in which case we should probably handle it correctly.

(layers-store) SpatialConversionUtils:: extractZippedShapeFile fails when extracting a zip file which contains a folder.

e.g. inside the zip file is:
/folder/shape.shp
/folder/shape.dbf etc

This format for a zipped shape file appears to be produced by at least one common-ish tool as I encounter them fairly frequently in MERIT support.  Either that or users are exporting the files un-zipped then zipping them up themselves at the folder level.

**Comment by adam-collins** [comment]
Fix is on spatial-dev for testing.

**Comment by adam-collins** [comment]
on prod
