### ISSUE TITLE
Add to Map | Areas | Select area from polygonal layer - behavior problems

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#104]
SP-DEV:

If I use Add to Map | Areas | Select from polygonal layer, select LGAs and then click on an LGA in WA and it produces a small square that is NOT the polygon. If I uncheck the 'My area' layer and then re-check it, the proper LGA polygon is mapped.

If I then unselect the My area layer and do another Add to Map | Areas | Select from polygonal layer, it goes straight to the 'Select area from polygonal layer' box in the legend and no layers are identified.

See attached screen captures (in sequence).
![capture](https://cloud.githubusercontent.com/assets/6656350/9103069/1a2755b8-3c3d-11e5-99af-9aed32311e71.jpg)

![capture_2](https://cloud.githubusercontent.com/assets/6656350/9103075/28ab6840-3c3d-11e5-82ac-38a7d5eab784.jpg)

![capture_3](https://cloud.githubusercontent.com/assets/6656350/9103080/32faeaaa-3c3d-11e5-936d-1f6915815b61.jpg)

![capture_4](https://cloud.githubusercontent.com/assets/6656350/9103082/39635562-3c3d-11e5-977f-4abafa099305.jpg)

![capture_5](https://cloud.githubusercontent.com/assets/6656350/9103084/411e8646-3c3d-11e5-8c37-89b15b6dd578.jpg)

**Comment by adam-collins** [comment]
Fixed on dev. The style assignment was missed when recreating the Objects layer in geoserver. This is not an issue on prod.
