### ISSUE TITLE
NRM Regions 2014 layer has errors

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/spatial-portal#105]
It appears when the NSW LLS regions were incorporated into the NRM layer, there were two regions with the same name as existing objects in the layer.  This appears to have resulted in those objects merging the two regions into a single object/feature.
The affected objects that I have found are "South East" (http://spatial.ala.org.au/ws/object/6239206) and "North West" (http://spatial.ala.org.au/ws/object/6239235)
If you check the geometry (e.g. http://spatial.ala.org.au/ws/shape/geojson/6239206) you can see the object has a MultiPolygon geometry containing both regions as separate polygons.

**Comment by adam-collins** [comment]
layers-service and geoserver updated. biocache resampling not yet done.

**Comment by chrisala** [comment]
Thanks Adam.  Some of the objects are not returning a bounding box when queried. e.g. http://spatial.ala.org.au/ws/object/6245181 (North West NSW).  Is this something that happens as a part of the sampling?

**Comment by adam-collins** [comment]
The bounding box is there now. This might have been done by a scheduled task.
