### ISSUE TITLE
Facetable field names mixing ids and names, and some ambiguous

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#106]
1. The current "Location" facets on Prod are a mixture of names, short names and UIDs. 
2. Names such as "Biogeographic region" are ambiguous
3. Names such as "min_elevation_d_rng" are not in spatial.ala.org.au/layers CSV
4. 'Location' facets don't match supplied list

Location facet names should come from "Name" field
![capture](https://cloud.githubusercontent.com/assets/6656350/9296186/09d34fb0-44ca-11e5-81da-efb5193c7714.jpg)

**Comment by adam-collins** [comment]
Layer names corrected. 

Need to discuss the rest.

**Comment by adam-collins** [comment]
SP side is done. Remainder at biocache-service issues 30 and 33.
