### ISSUE TITLE
Error 404 on Generate points

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#108]
Add to Map | Areas | Gazetteer polygon | Eucalypt Forest (temperate)
Tools | Generate points 0.1 degree within these polygons
After a few minutes - Error 404

**Comment by adam-collins** [comment]
An update to fix this is on prod.

**Comment by Tasilee** [comment]
Excellent! Tried it on a number of large and complex areas, and it worked fine.
