### ISSUE TITLE
Timeout on Area Report on 93,000 sqkm polygon

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#109]
Checking user problem of generating an area report on an imported kml polygon timed out. This isn't a huge area, but is a complex polygon (that had been simplied on import).

kml file - https://www.dropbox.com/s/54xe4ei6pfvsl2u/Eva%20Finsel%20-%20Einsleigh%20small.kml?dl=0

**Comment by adam-collins** [comment]
A change makes this much faster on prod today by simplifying the imported area to limit the number of points.

**Comment by Tasilee** [comment]
Looks good!
