### ISSUE TITLE
Scatterplot using Points to grid richness and density fails

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#111]
1. Selected a small area (20K sqkm)
2. Map all species
3. Points to grid (0.1, 9x9, density and richness layers)
4. Scatterplot using all species in area, density and richness layers ran but blank scatterplot produced. Checked 'standard' scatterplot and it worked so assume something wrong with re-use of richness and density layers.
![capture](https://cloud.githubusercontent.com/assets/6656350/10925728/cc8d71d6-82e4-11e5-92ce-c282181b90c5.jpg)

**Comment by adam-collins** [comment]
Scatterplot with density layers now displays. The interaction between the scatterplot and map is unavailable because the density layers are not indexed. Download data is available.

**Comment by Tasilee** [comment]
Prod: This works very well. Download data does however suffer from the same problem as elsewhere in that identifiers are used instead of names for the layers, e.g., for the first two layers- 

el874	1450047288247_odensity	environmental envelope area (sq km)

I really like the reporting of the environmental envelope area!

**Comment by adam-collins** [comment]
Download data column headers fixed on prod.

**Comment by Tasilee** [comment]
Much better!
