### ISSUE TITLE
Add new Add to Map | Area option - Contextual layer classes

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#116]
Fiddling with the Phylogenetic diversity tool, it would make more sense (as we did with merge areas), to add new areas defined by "Contextual layer classes" rather than having this specific option limited to Tools | Phylogenetic diversity? This option would tap the 'layers table' data to limit choices to appropriate contextual layers.

The phylo tool would then present this 'area' as with any previously defined (or on the fly) area.

**Comment by adam-collins** [comment]
Moved to AtlasOfLivingAustralia/spatial-hub#4
