### ISSUE TITLE
enable reuse of points to grid output layers 

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/spatial-portal#118]
Output layers from points to grid need to be available for reuse in the same way as classification, maxent and gdm output layers.

**Comment by adam-collins** [comment]
Export | Points sample needs a progress bar for large downloads and intersection of analysis output layers to prevent timeouts.

**Comment by Tasilee** [comment]
Points to grid density layer is available in scatterplot and MaxEnt but not in export sample? It also seems MaxEnt and scatterplot are failing if occurrence density layer is used in the mix.

**Comment by adam-collins** [comment]
Update on SP dev. 
- Reuse of Classification in Prediction may not work. Not tested.
- Reuse of generated grid layers appears to be working in classification, prediction, gdm, scatterplot, scatterplot lists.
- Reuse in scatterplots does not permit the drawing a bounding box on the scatterplot to update the map. This is because the analysis layers cannot be indexed.
- Reuse of all generated layers in Export | Point sample does work. A simple progress indicator prevents timeouts that may occur.

**Comment by Tasilee** [comment]
Re-use of points-to-grid occurrence density works well on scatterplot, classification, prediction and export | Point sample but the latter is odd in that it produces a standard output of points with DwC fields and flags as usual, and then when you click download again, it produces the intersect output with the id and the chosen layer values. I presume most would then do a left-right merge.

**Comment by adam-collins** [comment]
export | Point sample has always exported intersections with analysis output layers as a separate file. I guess it can be changed now.

**Comment by Tasilee** [comment]
Yes, if it is easy enough to combine the files. There are plenty of reasons for an integrated data file.

**Comment by adam-collins** [comment]
Leaving this as-is for now.
