### ISSUE TITLE
Select from Polygonal layer broken in prod

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/spatial-portal#119]
This now seems to skip the step in the wizard where the user selects the layer to use.

**Comment by Tasilee** [comment]
Which wizard, Add to Map | Areas - Select area from polygonal layer? The contextual/polygon legend now (also) enables class and unique polygon selection.

**Comment by djtfmartin** [comment]
Yeah, Add to Map | Areas - Select area from polygonal layer.

is it working for you ?

**Comment by Tasilee** [comment]
I tested it 15 minutes ago and it was working for me but it does operate differently than it did before. Previously, you needed to have the polygonal layer mapped and the wizard asked which of the mapped polygonal layers was to be used to select the polygon from. Now, it asks you to search/select the polygonal layer from the list of relevant (contextual) layers. This option is redundant now that we have changed the legend setup for polygonal/contextual layers, but two avenues are ok.

I just cleared the cache etc, and re-ran the option and it no longer asks for the layer. Hmm, figured it out....it looks like it will work (ask for layer) only if a polygonal/contextual layer has been mapped. If no polygonal layers are already mapped, it gets stuffed.

**Comment by djtfmartin** [comment]
its working all 3 ways for me locally, so i think its a bug with whats deployed.

**Comment by adam-collins** [comment]
Updated prod to fix it.

Add to Map | Areas - Select area from polygonal layer needs a little more work before this can be closed.

**Comment by Tasilee** [comment]
Problems with drop-down layer select
![capture](https://cloud.githubusercontent.com/assets/6656350/11699684/ac16e67a-9f19-11e5-959c-f849bed01428.jpg)

**Comment by adam-collins** [comment]
Updates on SP dev.

**Comment by Tasilee** [comment]
Nice work Adam! ToProd
