### ISSUE TITLE
Environmental envelope ranges need to be GE and LE

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#120]
Reported by Trevor Booth to me today. E. kruseana natural distribution is selected and scatterplot is used to show the range of conditions for the growth index (C3 mesotherm).  The range on the dendrogram for C3 mesotherm is 0.08 to 0.10 (as a rare species the actual locations are generalised to about 0.1 degree). The environmental envelope function in Map|Area is then chosen to map areas that satisfy this condition, the growth index (C3 mesotherm) is selected and the range 0.08 to 0.10 is entered but the points on the map are outside the envelope. 

Increasing the environmental range slightly (i.e. using 0.079 – 0.110 instead of 0.08 – 0.10) brings in the locations that would be expected to be within the range indicated by the original scatterplot. 

This may be due to the function using greater than lower bound value and less than upper bound value instead of greater than or equal to and less than or equal to.

**Comment by adam-collins** [comment]
Adding an internal buffer of 0.0000001 will correct for the data type conversion issue in this example.

**Comment by adam-collins** [comment]
On Prod.

**Comment by Tasilee** [comment]
Trevor and I have checked it out and it looks good!
