### ISSUE TITLE
Area report species groups listing in error

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#121]
An area report for Mariah Island (Tasmania) reported 1700 species in total, 1700 invasive species and 1700 endangered species. This is obviously not correct.
![capture](https://cloud.githubusercontent.com/assets/6656350/12185762/3092833a-b5f1-11e5-9e90-0bcca7663f0d.jpg)

**Comment by adam-collins** [comment]
biocache-service needs to be redeployed to pick up the fix for this.

**Comment by Tasilee** [comment]
Tests ok across all lists using an area defined by elevation > 2000m. Mapped area doesn't encompass all locations but sampling does so will add note to help.
