### ISSUE TITLE
Scatterplots not showing in legend area

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#122]
See image. Scatterplot of E.gunnii and E.Elata (background) on Bio01+Bio12 with possible environments gives blank scatterplot area in legend.
![capture_3](https://cloud.githubusercontent.com/assets/6656350/12186102/c3956ed4-b5f3-11e5-8eda-c6c36a66f3b0.jpg)

**Comment by adam-collins** [comment]
Unable to reproduce this error.

**Comment by Tasilee** [comment]
Closer review: the BASIC (foreground species) works but add a background species and it is blank with rectangle drawing. With or without 'possible environments' - blank.

**Comment by adam-collins** [comment]
On Prod. The scatterplot now displays correctly when the selected background species has no occurrences in the area.

**Comment by Tasilee** [comment]
Checks out: Nice work
