### ISSUE TITLE
Improve scatterplot - prevent background layer from being covered by active layer

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/spatial-portal#123]
Request from Nola:

> Would it be possible to request that your system is altered to allow the imported points not to be hidden (i.e. bring the imported points to the front), as happens on the distribution map? This additional function would greatly increase the usability of the ALA scatterplot function.
I will also ask Trevor Booth how he has managed to produce the imported point on the scatterplot because he is involved in the Guide I am writing. 

See screenshot were purple dot (background layer) is not visible on scatterplot:

![ala](https://cloud.githubusercontent.com/assets/532845/13130933/6c4ccfbe-d63c-11e5-95f4-648fb1e75296.png)

Maybe have an option to "show background layer on top of species layer" ?

**Comment by nickdos** [comment]
Upload file used:

[Targetsite-species.txt](https://github.com/AtlasOfLivingAustralia/spatial-portal/files/135559/Targetsite-species.txt)

**Comment by Tasilee** [comment]
If I am interpreting correctly, all that needs to be done is to use the imported points as the foreground layer on the scatterplot, with E Melliodora as the background species?

![capture](https://cloud.githubusercontent.com/assets/6656350/13158796/ba1be800-d6e2-11e5-9ef3-d61083f790c7.jpg)

**Comment by adam-collins** [comment]
I was reading this as a request to add display settings for background species. Users can swap foreground and background species selections in the scatterplot but can currently only control the display of the foreground points.

I think this is a low priority given that users can export the foreground scatterplot coordinates and do whatever they like.

There was an earlier observation that scatterplot would fail if the imported point did not have a species or scientificName column but I cannot reproduce this.

**Comment by Tasilee** [comment]
If there is a background 'species', a generic solution would be to add a selector button to the scatterplot legend pop up to enable the same display functionality to apply to either the foreground or background species?

**Comment by nickdos** [comment]
I also suggested swapping the layers Lee, but the use case is they want to be able to see the single "site" layer (single dot) while manipulating the the selection of the active layer (Euc) both via the map and the scatterplot. 

Adam says:
> I think this is a low priority given that users can export the foreground scatterplot coordinates and do whatever they like.

What they want is to be able to click on the map or scatterplot and explore the relationships with the environmental values for the Euc layer while still being able to see the site layer. Exporting the plot data doesn't help here, unless I'm missing something.

If they export the Eucalpytus layer and then merge their site dots into the one CSV and import it as the active layer, is this the idea? If so how can you ensure the site dots remain "on top" of the other dots?

**Comment by adam-collins** [comment]
For this specific use case I would suggest using an area instead of a point to represent the site.

Create an area with Add to map | Area | Create radius from point and use at least a 3km radius at the example point so that some E Melliodora occurences are included in this area. Create a scatterplot with foreground species E Melliodora. Above the scatterplot itself there is a drop down where the created area can be selected. The scatterplot occurrences that fall within the selected area are highlighted on the scatterplot itself. 

![scatterplot](https://cloud.githubusercontent.com/assets/8031500/13167824/9b432f5c-d722-11e5-8998-e56783a22d1d.jpg)

**Comment by Tasilee** [comment]
An elegant solution Adam.

**Comment by nickdos** [comment]
Its still a bit too clunky I think. The 3 km radius was not enough as the dot was invisible if I was at a zoom level that showed both Vic and NSW. So I had to go back and recreate it until I had a size that was visible for the zoom I wanted. This will be different for each case so will be trial and error - which is annoying. I also think they will want to view a number of sites so adding each one individually is too much work, compared to using a CSV upload.

This particular user is putting together a user guide in partnership with Trevor Booth, so this use case is considered to them as being worthwhile enough to want to use it as example.

> As I mentioned, I am writing a guide for practitioners on how to select species for revegetation and want to give instructions on how to use certain parts of the ALA. 
> [snip]
> I will also ask Trevor Booth how he has managed to produce the imported point on the scatterplot because he is involved in the Guide I am writing.

**Comment by nickdos** [comment]
Another problem with the "create radius from point" is you have to set a large radius to see the point on the map (mentioned already) but this results in a scatterplot that show multiple circles on the plot due to the large (and varied) sampling within the radius area (feature not bug). But for this scenario, its not what the user wants.

I think the "point from radius" should display just like any occurrence record - you should be able to set the display radius in pixels. The radius value should be treated just the like the coordinate uncertainty for a record - which we don't generally show. But you could add an option to display it (toggle).

Does this warrant a new issue?

**Comment by nickdos** [comment]
Info from Nola:

> I have used the example of Eucalyptus melliodora. I want to plant this species at a particular location.
> Example site near Albury, 146.95, -36.01
However, I want to assess if this species will still be suitable by the end of the century, with higher temperature and changed rainfall patterns. So I do a species occurrence map to see what the current distribution of the species is. I see that it has a wide distribution. I import the above points and I can see that my site (near Albury) is within the current range. I then do a scatter plot using Biol01 (temp) and bio12 (precip). I want to see where my planting site is on that plot so that I can visually assess if the species will still be suitable at my site if there is say a 3C rise in temperature and a 20% fall in precipitation. Currently, I can't see where my planting site is on the scatterplot.
> There is only one site.

**Comment by Tasilee** [comment]
I discussed the use of the point to area option with Nola via phone and a few emails and she finds the solution nicely addresses her needs. I will add the process to the Scatterplot help.
