### ISSUE TITLE
point sample of Sandbox occurrences does not include dynamic columns.

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/spatial-portal#126]
Uploads to the sandbox that include unmatched columns are not including these dynamic columns in the point sample.

**Comment by Tasilee** [comment]
Conforming: Unmatched column names via Sandbox are not included in Export | point sample.  

Sandbox related issues: 

1. When yellow/unmatched columns are renamed to Darwin Core terms - e.g., "locality"), they remain yellow after "reprocess data".

2. "Upload data" doesn't appear to do anything for ~ 20 seconds.

Test CSV dataset that has columns (Project, Longitude, Latitude, MW, Status, State):  Longitude, latitude, State matched. If imported as is (unchanged headers), Project, MW and Status are available as facets but do not export on Export | Point sample.

If the table header "Project" is renamed in the Sandbox to "locality" then uploaded, it is NOT available as a facet BUT the column does export in Export | Point sample!

If the table header "MW" is renamed in the Sandbox to "verbatimElevation" then uploaded, it is NOT available as a facet and does not form a column in Export | point sample.

Odd inconsistencies? Test dataset (as xlsx) attached.
[Windfarms.xlsx](https://github.com/AtlasOfLivingAustralia/spatial-portal/files/368285/Windfarms.xlsx)
