### ISSUE TITLE
Highlight of scatterplot points using analysis layers fails due to no indexing

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#127]
A current limitation of the scatterplot tool is the highlighting of selected scatterplot points on the map when using layers that have been produced from analyses. The reason for this is that the layer has not been indexed against the points used to generate the scatterplot. Layers produced on the fly cannot as yet be 'sampled' by the occurrence records.

A message is placed above the scatterplot saying that the analysis layer is not indexed.
![capture](https://cloud.githubusercontent.com/assets/6656350/13587270/1f584ede-e51b-11e5-8353-5eb54afb2a6f.jpg)

**Comment by adam-collins** [comment]
Because it is not possible to do this look displaying an environmental envelope on the map instead of highlighting points on the map.

**Comment by Tasilee** [comment]
AOK. Thanks Adam

**Comment by adam-collins** [comment]
Moved to AtlasOfLivingAustralia/spatial-hub#2
