### ISSUE TITLE
Add to Map | Species needs ability to generate area

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#128]
Most of the wizards permit the defining of an AREA on the fly but not for Add to Map | Species. It currently only permits the subset - Current extent, Australia and World.

The ability to use the  Add to Map | Area options would be nice, and consistent.

**Comment by Tasilee** [comment]
Upped to critical as I really need this function for a workshop next Thursday (16th). Possible to reinstate?

**Comment by adam-collins** [comment]
on prod

**Comment by Tasilee** [comment]
Neat
