### ISSUE TITLE
Use layers table (as in Add to Map | Layers) in layer selection of Scatterplot (user feedback)

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/spatial-portal#129]
> Hello
When using the scatterplot function in ALA, is there a glossary explaining the environmental layers available for use in the plot please? There is an environmental layer list available at http://spatial.ala.org.au/layers but this doesn't always have an explanation and it is hard to find the variable because the variable does not appear in alphabetical order.
Thank you
Nola

**Comment by Tasilee** [comment]
The layer list as presented is in alphabetical order and can be searched via long name, short name, tags. There was one layer named "ph" that is better rendered "Ph" for sorting.

If feasible, it would be better to use the layer table as presented via 'Add to Map | Layers' with a test for 2 and only 2 layers selected. The current "Mapped Layers" option (layers produced in SP) are available at the top of the table so I can't see any issue?

**Comment by adam-collins** [comment]
on prod

**Comment by Tasilee** [comment]
Dandy!
