### ISSUE TITLE
Species track data - machine observations

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/spatial-portal#13]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=95
*date:* Thu Aug  8 16:21:41 2013
*author:* moyesyside
 ---

Original Issue reported by Project Member Reported by leebel...@gmail.com, Dec 8, 2011 - [https://code.google.com/p/alageospatialportal/issues/detail?id=811](https://code.google.com/p/alageospatialportal/issues/detail?id=811)

Project Member Reported by leebel...@gmail.com, Dec 8, 2011 
There is a large volume of species tracking data available that would be useful to add to the existing point occurrences, checklists and expert distributions. 

The structure is a species located at a point at a given date/time and possibly depth/height/temperature etc values. The points,  connected by shortest path form a time/location vector.

A first step may be be an area-intersection with the points. For this, DwC records of each point observation would do. Ideally, we would want to determine an intersection of a track without points with an area. Harder.

Seems like a Dave problem to start with?

 Dec 8, 2011 Project Member `#1` leebel...@gmail.com 
Donald:

My thinking was that there were two quick wins here:

1.	Simply offer layers from IMOS for species tracks for inclusion in the ALA Spatial Portal as additional map layers (perhaps discoverable in a similar way to the expert distributions) purely for display and for linking back to the IMOS data.

2.	See whether these sensors on the west coast that detect when certain tagged fish come near them can be treated as streams of DwC records for the fish species in question.

Clearly we can do more, but some rapid progress in working with IMOS would be valuable.

 Mar 15, 2012 Project Member `#2` leebel...@gmail.com 
Doubt this will be possible b4 June 30 2012.
 Labels: -Priority-Medium Priority-Low

**Comment by adam-collins** [comment]
Moved to AtlasOfLivingAustralia/spatial-service#41
