### ISSUE TITLE
Gazetteer points not mapped

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#132]
Add to Map | Areas | Gazetteer polygon

It looks like at least some gazetteer point (2012 tried) are not being mapped. For example, "Merricks Creek" in Victoria is in the gazetteer (2012) and zoom to extent works but there is no circle mapped. Also tried the same creek in NSW, same outcome.

**Comment by Tasilee** [comment]
Confirmed this again with "Barrow Island airport" (gaz 2012)

**Comment by adam-collins** [comment]
on prod

**Comment by Tasilee** [comment]
Skull Springs (2012 gaz) WA 1km radius produced

Failed to process 
script
Cannot read property 'style' of null (TypeError)

**Comment by adam-collins** [comment]
I cannot reproduce the script error. Might be a clear cache issue.

**Comment by Tasilee** [comment]
Re-tested OK.
