### ISSUE TITLE
Area report - endemics not 100% correct

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#133]
Area: POLYGON((115.21 -20.927,115.556 -20.927,115.556 -20.662,115.21 -20.662,115.21 -20.927)). Genus Austroteneriffia not endemic to area. 

Other 14 reported taxa are endemic but two taxa Barrowammo waldockae reports 3 occurrences but 6 appear to be there. Ditto, genus Dictus reports 1 occurrence and 6 appear to be there.
[Endemics - Barrow Island area.xlsx](https://github.com/AtlasOfLivingAustralia/spatial-portal/files/368230/Endemics.-.Barrow.Island.area.xlsx)

**Comment by adam-collins** [comment]
Genus level matches in the species list imply that the species is unknown. With this in mind there appears to be no issue with the occurrence counts identified in the file today.

**Comment by Tasilee** [comment]
Yep, I buy that from checks so far.
