### ISSUE TITLE
Tools | Tabulation not working

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#134]
Running Tools | Tabulation there are two problems

1. Can't select most combination of layers - forced to State/Territories vs IBRA 7
2. Result of any comparison is a new window with message as attached

![capture_2](https://cloud.githubusercontent.com/assets/6656350/16905577/739542d0-4ceb-11e6-9863-0bb7e55f9174.jpg)

**Comment by adam-collins** [comment]
Fixed.
