### ISSUE TITLE
Specieslist add-to-map error

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/spatial-portal#135]
I did the following:

- view northern part of WA
- add to map -> species
- use existing species list
- search for `EPBC` and choose `Australia wide : conservation status : EPBC", next
- select `current extent`, next
 get error message: `-1 occurrences in this area - select an area with fewer than 20000000 occurrences`

screenshots:
![spatial_portal___atlas_of_living_australia](https://cloud.githubusercontent.com/assets/532845/17014013/64d56924-4f65-11e6-9e7f-fc9e602bac63.png)
![spatial_portal___atlas_of_living_australia](https://cloud.githubusercontent.com/assets/532845/17014020/701e55d4-4f65-11e6-826b-db25f65f35ca.png)
![spatial_portal___atlas_of_living_australia](https://cloud.githubusercontent.com/assets/532845/17014023/753f46fe-4f65-11e6-9361-c0d2b6e78abf.png)

**Comment by adam-collins** [comment]
This is the result of the SOLR error 'too many boolean terms'. The solution is to match the SOLR limit of 200 'OR' terms. 

Also changing text to "Use existing species list (limited to 200 species)"

**Comment by Tasilee** [comment]
Thanks Adam. Will the result be the first 200 taxa (probably best) or a "go away"?

**Comment by adam-collins** [comment]
on prod

**Comment by Tasilee** [comment]
Thanks Adam. The SOLR limit presents a problem for effective use of larger lists (and 200 isn't a huge number, sadly). Currently, we can find out WHICH 200 species have been plotted by using the (i) button (metadata). If I do that for Nick's example, I got 153 species and I guess I could copy these and compare them with the list to see what wasn't plotted.

Could I be bold and suggest a strategy that would be ok for lists > 200? Map ~200 species at a time - one per point layer? Then the ORDER of mapping needs to be considered. Random would not be good. Alphabetic by scientific name would seem the simplest and most expedient.

**Comment by Tasilee** [comment]
Small suggestion: It would be useful to be able to DOWNLOAD the info on the metadata window to a text file.

**Comment by adam-collins** [comment]
This is worth considering in all places species lists are available for use. Moving to AtlasOfLivingAustralia/spatial-hub#1
