### ISSUE TITLE
Add in/out layers to map not working properly

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#137]
Using a scatterplot layer. 

The pop-up on points was displaying twice the number of occurrences at the points. Assuming it was picking up the original occurrence layer + Scatterplot point layer.

I selected > 12 points and did "Add in/out layers to map" and 'out' layer retained all 'in' layer points. On selection, it was saying "10 points selected"
![capture_2](https://cloud.githubusercontent.com/assets/6656350/17090113/adf16dca-5270-11e6-8ac1-5a5b3b0d51e0.jpg)

**Comment by adam-collins** [comment]
Adding the layer name to the occurrence information popup to indicated the source of the occurrence in case the same occurrence appears in more than one layer at the point clicked.

Removing the duplicate occurrences that were included when there was a scatterplot highlight (red circle) at the point clicked.

**Comment by adam-collins** [comment]
on prod

**Comment by Tasilee** [comment]
Checks out ok
