### ISSUE TITLE
Autocomplete issues

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#138]
Problems with the current names autocomplete in the SP-

1. Fuzzy matches should not be reported, e.g., "Eucalyptus gunnii" reports 13 non-Eucalyptus genus entries at the top of the list.

2. "Eucalyptus" returns the genus as last in the list. Not nice.

3. Taxa with no occurrences need to be included in the list, if they match the autocomplete. In most cases, getting a match, even if zero occurrences, is very important. It informs that we have the name, but no records (identifies a gap). This could be an optional check box, given (4) below...

4. There are usually far too many entries returned in the list. There are currently 20 entries that match "Eucalyptus gunnii" and 80 that don't. Of the 20, there are 5 seeming duplicates - see (5).

5.  Entries like this make no sense at all-

Eucalyptus gunnii var. montana
species, - found 616
Eucalyptus gunnii var. montana
species, - found 1715 +2 expert distributions

and

Eucalyptus gunnii var. rubida
subspecies, - found 5620
Eucalyptus gunnii var. rubida
subspecies, - found 1432

and 

Eucalyptus gunnii var. undulata
variety, - found 0
Eucalyptus gunnii var. undulata
variety, - found 0

and

Eucalyptus gunnii
species, - found 343
Eucalyptus gunnii
species, - found 1715 +2 expert distributions
Eucalyptus gunnii
variety, - found 3479

**Comment by djtfmartin** [comment]
agree this isnt good. This needs to be fixed in bie-index. Moving to bie-index

**Comment by djtfmartin** [comment]
This issue was moved to AtlasOfLivingAustralia/bie-index#92
