### ISSUE TITLE
Area report for "World" fails for "occurrences" and "Number of species"

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/spatial-portal#140]
<img width="686" alt="screenshot 2016-09-14 14 52 48" src="https://cloud.githubusercontent.com/assets/444897/18514820/f026e4da-7a8a-11e6-837f-69a772e60c7f.png">

**Comment by djtfmartin** [comment]
Ive got a fix here in this fork

https://github.com/nbnuk/spatial-portal/commit/a32b9069fd2aeb8c5fb80a09c4ead7bf9fddd625

**Comment by adam-collins** [comment]
Merged the fix
