### ISSUE TITLE
List from Area report - threatened species - should contain threatened values

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/spatial-portal#144]
User has imported KML file, run an area report and clicked the "List" button next to the "Threatened species" entry. Resulting file contains a column for "Conservation" but only lists the source list, not the value (threatened or least concerned). The user wants to filter the list by species with a certain value, but is unable to.

**Comment by adam-collins** [comment]
moved to https://github.com/AtlasOfLivingAustralia/specieslist-webapp/issues/92
