### ISSUE TITLE
The names of two IMCRA 4 meso-scale bioregions are misspelt

### ISSUE THREAD

**Issue by ben3000** [AtlasOfLivingAustralia/spatial-portal#145]
See the output of web service API calls:

- http://spatial.ala.org.au/layers-service/object/5724985
- http://spatial.ala.org.au/layers-service/object/5725033

They should be "Pilbara (nearshore)" and "Pilbara (offshore)". See reference at:

http://www.environment.gov.au/resource/guide-integrated-marine-and-coastal-regionalisation-australia-version-40-june-2006-imcra

**Comment by adam-collins** [comment]
moved to https://github.com/AtlasOfLivingAustralia/layers-service/issues/104
