### ISSUE TITLE
Better docs for - include spatially valid/suspect records

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/spatial-portal#152]
E.g. Choose add to map -> species

![image](https://user-images.githubusercontent.com/532845/38713039-93370252-3f12-11e8-9ead-e4765653a8f3.png)

There is a help page but these options are not mentioned.

https://www.ala.org.au/spatial-portal-help/species-add-to-map/

If neither option is selected, would I expect to see zero records? EDIT, JS code prevents de-selecting both, but the fact that its looks like you can do this, is confusing in itself.

This is quite confusing and should be explained in detail somewhere. E.g. what is actually applied to each option in terms of facets filters, etc.

**Comment by ansell** [comment]
+1, the processes that are used to make the decision right now for ``spatially-suspect`` and ``geospatial_kosher`` are not clear in terms of either the interface or the code documentation.

Is the following the complete list of tests that are done?:

https://github.com/AtlasOfLivingAustralia/biocache-store/blob/2.x/src/main/scala/au/org/ala/biocache/vocab/AssertionCodes.scala#L14...L67

There is also an interesting method named ``getHackValue`` that appears to also have another decision point that may be relevant:

https://github.com/AtlasOfLivingAustralia/biocache-store/blob/2.x/src/main/scala/au/org/ala/biocache/dao/OccurrenceDAOImpl.scala#L343...L360
