### ISSUE TITLE
Switch to production

### ISSUE THREAD

**Issue by kheerand** [AtlasOfLivingAustralia/spatial-portal#154]
Cover off the things that are needed to make it a production service.

- [ ] [Release Checklist](https://confluence.csiro.au/display/ALASD/Release+Checklist)

**Comment by Tasilee** [comment]
There is no new functionality in the beta Spatial Portal. There are however some minor formatting differences that I am aware of. In the current version, each step of the wizards are on a separate page on a pop-up window. In the beta, all steps are on a single scroll-able page.  

1. The Google zoom bar has been simplified. Zoom to user location is not implemented in the beta
2. The rollover value (existing) versus click at location (beta) for displaying environmental/contextual layer values
3. Slightly different formatting of scale bar and coordinates at cursor
4. Header bar content and format has been changed (contact us, get involved ALA apps, save session, user settings to save session, load session, user settings, ALA home page)
5. Species point pop-up (beta) displays (in addition to existing version info) "List records at this point"
6. Display user-images on map used the now defunct Google Panoramio and now uses Flickr (but it operates exactly the same).
