### ISSUE TITLE
Report on Spatial Portal usage

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#167]
We do not have an ability to produce a report of Spatial Portal usage. At this time, when my position is being replaced, it will be important to review usage to assist in setting priorities for addressing outstanding issues and plotting a pathway ahead. Ideally, the report should produce a CSV file as per attached template.
[Spatial Portal User report.xlsx](https://github.com/AtlasOfLivingAustralia/spatial-portal/files/4162158/Spatial.Portal.User.report.xlsx)

**Comment by nickdos** [comment]
Issue moved to [AtlasOfLivingAustralia/spatial-hub #278](https://github.com/AtlasOfLivingAustralia/spatial-hub/issues/278) via [**ZenHub**](https://www.zenhub.com/)
