### ISSUE TITLE
Analysis tools cannot handle large grids

### ISSUE THREAD

**Issue by mbohun** [AtlasOfLivingAustralia/spatial-portal#18]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=500
*date:* Sun Dec 22 19:48:45 2013
*author:* chris.fl...@gmail.com
 ---

This problem was discovered when loading a large grid file as part of the fieldcapture work.

Some of the analysis tools make the assumption that all grid files can be read into byte arrays. These tools fail when reading a grid file containing a number of bytes larger than the maximum array size in Java.

This problem occurs in the GridLegend tool and the Intersect service, but it may occur elsewhere.

I have fixed the problem in the Bil2Diva tool by iterating over grid files one megabyte at time.

**Comment by adam-collins** [comment]
Done
