### ISSUE TITLE
Wordpress Static content out of date for Layers

### ISSUE THREAD

**Issue by mbohun** [AtlasOfLivingAustralia/spatial-portal#19]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=507
*date:* Tue Jan  7 18:48:03 2014
*author:* natasha....@csiro.au
 ---

The static content on the [http://www.ala.org.au/mapping-analysis/layer-list/](http://www.ala.org.au/mapping-analysis/layer-list/)
page is out of date. 

It should be [http://spatial.ala.org.au/layers](http://spatial.ala.org.au/layers)

This was discovered by Linda when she performed a ALA search for layers and looked the Site Page filter: [http://bie.ala.org.au/search?q=layers&fq=idxtype:WORDPRESS](http://bie.ala.org.au/search?q=layers&fq=idxtype:WORDPRESS)

It may highlight an issue that some of the documentation for the layers and spatial stuff is not available from the standard ALA search.  Thus making it difficult for normal users to locate the information.

**Comment by adam-collins** [comment]
Looks like there is a link to the live page.
