### ISSUE TITLE
Tabulations outstanding issues

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#22]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=547
*date:* Mon Jan 27 16:59:46 2014
*author:* leebel...@gmail.com
 ---

In writing a Case Study on Tabulations (Tools | Tabulate), I note a number of outstanding Tabulation issues

1. Defect: The drop down list includes a typo "Tillage practive - dominant (area)(class)". I am unsure where the list comes from as it is ok in the Layers Table (where I can edit it).

2. Enhancement: The tabulations are currently missing the contextual layers

   Surface geology (`#60` Miles to get 250m grid data from Kristen Williams)
   Koppen Climate Classification*
   Koppen Climate Classification – sub areas*
   Land Cover Type – IGBP (2011)*

**Comment by Tasilee** [comment]
Seems like new contextual layers are unavailable for tabulation. The ingestion process should include cross-tabulation of suitable layers where suitable = multi-class, national extent.

**Comment by Tasilee** [comment]
See also #44

**Comment by Tasilee** [comment]
I assume the number of species and number of occurrences would need at least monthly updating?

**Comment by Tasilee** [comment]
Tabulation currently down so cannot check status of this issue.

**Comment by adam-collins** [comment]
Current tabulation issues are addressed in spatial-service.
