### ISSUE TITLE
Surface Geology layer fails in use with MaxEnt (Prediction)

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#23]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=576
*date:* Tue Feb 11 14:05:30 2014
*author:* leebel...@gmail.com
 ---

Possibly related to `#547`. User picked detected that when the surface geology layer (a complex 250m layer very similar to dynamic land cover) is used in a Prediction, the system fails. Failure validated: See process/analysis ID: 1392155115716

Prediction does however work with dynamic land cover so I think it may be that surface geology has not been fully 'processed' into the system (which DLC has).

User who detected this issue has been notified (cc support@ala)

**Comment by Tasilee** [comment]
Issue remains - raising priority as this needs to fixed asap.
![capture_2](https://cloud.githubusercontent.com/assets/6656350/7464054/80f1b4b6-f302-11e4-91ae-6a8ec28dac18.jpg)

**Comment by adam-collins** [comment]
Working on prod. Please test.

**Comment by Tasilee** [comment]
ID 1439443065620 (e.camaldulensis, national, 5 env, 1 context) worked well
ID 1439444100055 (e.gunnii, tas, 30+ layers) failed

**Comment by adam-collins** [comment]
Working on prod.

**Comment by Tasilee** [comment]
Perfect! Tried with many layer combinations without problems.
