### ISSUE TITLE
Add ability to be able to use classification layer in area selection and tabulations

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#27]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=645
*date:* Tue Apr 22 00:15:51 2014
*author:* leebel...@gmail.com
 ---

Environmental domains that result from the Tools | Classification function are extremely powerful bioregionalisations (contextual layers) that we currently cannot make full use of.

Environmental domains have great power when consistent and comprehensive biological data is not available - which is most of the time.

We therefore need the ability to

1. Use Add to Map | Areas | Select area from polygonal layer and

2. The ability to intersect the environmental domains with other contextual layers would enable sophisticated evaluation of biodiversity options.

**Comment by adam-collins** [comment]
Moved to AtlasOfLivingAustralia/spatial-service#40
