### ISSUE TITLE
Implied absence data in at least one dataset raises procedural issue

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#29]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=703
*date:* Sun Jun 15 22:21:05 2014
*author:* leebel...@gmail.com
 ---

A placeholder for now:

I had a discussion with Mike Austin (CSIRO) about a dataset quite a few of us have worked on (Mike, Margaret Cawsey, Nick Nicholls etc) and it transpires at least one version of this dataset has come into the ALA via NSW Parks or subsequent equivalent.

The dataset contains the presence of TREE species in .25 or .1ha sites. The implication is that we can infer many absences of tree species on all of these ~10,000 sites. This would imply we could have of the order of ~>100,000 absence records.

It should be possible to automate or at least semi-automate the generation of these absence records at the survey sites using known tree distributions (via a geographic or environmental convex hull or equivalent)? 

This issue has also exposed another GAP in the ALA: The inability to generate sites x species matrices from survey points. This was what Mike Austin was asking about at the ALA Symposium. If we eventually get AEKOS data or any other bio-survey data, this will be a BASIC requirement. This is a separate but related issue that I'll raise.

**Comment by Tasilee** [comment]
occurrenceStatus="Absence" records need to be removed from all analyses (AOO and EOO, scatterplot, scatterplot list, Compare areas, Points to grid, Predict and GDM).

**Comment by adam-collins** [comment]
Absences are removed from all tools.

Absences are not removed from add to map species.
