### ISSUE TITLE
Tools | Generate sites x species matrix from survey points

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#30]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=704
*date:* Sun Jun 15 22:30:56 2014
*author:* leebel...@gmail.com
 ---

It would appear that we have a range of systematic survey sites in the ALA, some from NSW tree surveys with additions at least in SE NSW from a range of other agencies including CSIRO.

Tools | points to grid generates a sites x species matrix but is applicable for 'presence-only' observations. Systematic survey sites require the generation of a direct (survey) sites x species matrix or what Mike Austin refers to as a co-occurrence matrix. 

For this to occur our records must identify all survey sites where all  species in a 'category' were observed (e.g., trees, birds, grasses). This will imply a heap of absences. 

See `#703`

**Comment by adam-collins** [comment]
Moved to AtlasOfLivingAustralia/spatial-service#39
