### ISSUE TITLE
Add Collector field to advanced search form for ALA

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#31]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=708
*date:* Tue Jun 17 21:13:13 2014
*author:* leebel...@gmail.com
 ---

I'm trying to track down (preferably by SP) records associated with a collector but there are so many classes (collectors), there is no practical way to find them. An associated search for facets (I use the term for fields exposed in the ALA portals vs ws) when the number of classes exceeds ~30 (a few pages) seems badly needed. I've set High as currently some facets can't be used.

Being able to click on headings for "Class" and "Count" to sort up/down would also help.

**Comment by adam-collins** [comment]
Now preserving user selection between searches. Added button to clear selection from list items no longer visible in the current search.

**Comment by Tasilee** [comment]
Nice work Adam but (sorry) ran into a minor problem on selecting my third facet class. 
![capture_4](https://cloud.githubusercontent.com/assets/6656350/5716363/3ad41172-9b41-11e4-9000-71b59a210a33.jpg)
If I carry on, it does seems to work though.

**Comment by adam-collins** [comment]
error fixed
