### ISSUE TITLE
Add select box/generate selected layer for contextual layers with multi-class legends

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#38]
Currently, it is difficult to select and identify multiple polygons from one or more contextual layers that have multi-class legends. It seems consistent to offer the parallel to facet class selection and layer generation to contextual layers.

**Comment by adam-collins** [comment]
Contextual layer styles are stored in Geoserver. To make a checkbox list available the styles would need to be moved in layers-service and passed on to Geoserver as required.

A simpler option is a combo box with a list of the layer features available for selection and faceting. This only permits single feature selection.

This is on prod now.

**Comment by Tasilee** [comment]
Fair solution under the (technical) circumstances Adam and it seems to work ok, parallels the Add to Map | Areas | Gazetteer polygon. Defining an area from multiple classes/polygons still means an Add to Map | Areas | Merge areas.

Combo box seems, slow at first, unsorted? and double-spaced. But it works.
