### ISSUE TITLE
Legend for NZ DOC Public Conservation Areas (cl1061) too small to read

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#41]
The legend for cl1061 is very small and very hard to read.
![capture](https://cloud.githubusercontent.com/assets/6656350/4695652/149eb28c-5857-11e4-860c-339975e037b6.jpg)

**Comment by adam-collins** [comment]
If #38 does not help, would a popup with a larger legend be useful?

**Comment by Tasilee** [comment]
#38 adds functionality as it gets access to individual polygons (but they should be ordered alphabetically), but it doesn't make the legend classes any easier to read.

**Comment by adam-collins** [comment]
Sorted and using the area names not the layer class names. On dev and prod.

**Comment by Tasilee** [comment]
Still pretty darn small

![capture_2](https://cloud.githubusercontent.com/assets/6656350/6661368/490e8486-cbff-11e4-89e8-6cd2d1416ab6.jpg)

**Comment by adam-collins** [comment]
Updates on dev. 

A popup option to make the legend bigger added.

Using a list box instead of a drop down for the highlight group, with paging and filtering. It has zoom and a (+) to create an area layer from the list.

**Comment by Tasilee** [comment]
Legend (pop-up or otherwise) is single colour (grey) not reflecting the classification? Pop-up is a good option but note you can generate multiple pop-ups rather than re-exposing original.

**Comment by adam-collins** [comment]
Duplicate popups are prevented. That bad nz doc legend was only on dev and is fixed on dev.
