### ISSUE TITLE
Is it possible to replace 'non-unique' marginal totals in Tabulation with accurate values?

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#44]
Currently, (cross-) tabulations of SPECIES currently sums the number of species in the rows and columns to produce the marginal totals that are correctly labelled 'non-unique'. This therefore can't account for the same species occurring in multiple rows or columns. The same is true for the grand total of the table.

This creates an issue when someone is trying to determine, for example, how well parks/reserves etc may cover/protect species. To address that type of question, we need accurate species count totals on all rows and columns and the grand total of the species tables. For the above example, we should be able to determine how many species occur in all national parks and in all types of parks/reserves, or in one State or in all States and Territories if the second layer was States/Territories. This is currently not possible as we can only tell how many species occur in the combination of one park type AND in one State or Territory (using this example).

**Comment by adam-collins** [comment]
on prod
