### ISSUE TITLE
Add MERIT projects to Area Reports

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#46]
It can be difficult tracking information about a project or institution in the ALA. MERIT has the projects linked to organizations and sites (point locations). It would therefore be useful to report on projects in an area (Area Report) with links back to MERIT info. This would represent a very useful advance in the ease of finding info.
![capture_4](https://cloud.githubusercontent.com/assets/6656350/4970153/4b2e6cec-687a-11e4-8192-f4e6eaf8b473.jpg)

**Comment by adam-collins** [comment]
Moved to AtlasOfLivingAustralia/spatial-hub#3
