### ISSUE TITLE
Replace 2010 gazetteer with 2012 gazetteer

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#47]
See http://www.ga.gov.au/search/index.html#/download

The 2010 gazetteer has rounding errors on all locations so it should be replaced asap by the 2012 release (which was to address the 2010 problems).

**Comment by Tasilee** [comment]
Location errors due to truncation in the 2010 gazetteer suggest that we need to update to the latest version (2012) as soon as practicable. The issue has been around for 6 months.

**Comment by Tasilee** [comment]
Can we progress this please? The 2010 gazetteer's location errors are an ongoing problem.

**Comment by Tasilee** [comment]
(I have a copy of the data)

**Comment by adam-collins** [comment]
on prod.
