### ISSUE TITLE
Add search to species List select as there are now too many to page

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#49]
From ALA Workshop user:

"I was at the ALA workshop today and I wanted to recreate the mangrove species of Australia map showing the range of species.
When I go to "add to map' species, choose use existing species list, I see all the species lists and can not search in them - I have to scroll trough 33 pages to find the mangrove layers. Could you let me know when/if this option could be available?"

That says it all.

**Comment by djtfmartin** [comment]
The search services for the list tool are now in production

**Comment by adam-collins** [comment]
Removed the incorrect error message popup.
