### ISSUE TITLE
Site-based images ideas (Peter Doherty)

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/spatial-portal#5]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=74
*date:* Thu Aug  8 05:39:34 2013
*author:* moyesyside
 ---

Original Issue  - [https://code.google.com/p/alageospatialportal/issues/detail?id=972](https://code.google.com/p/alageospatialportal/issues/detail?id=972)

Project Member Reported by leebel...@gmail.com, May 8, 2012 
Hi, all - I've been referring to this myself as "experimental" as I would think the medium/longer term goal is to be able to, in a more advanced way do the following:
	1) Find sites/plots/survey areas 
	2) Find the above that have images over time
	3) Have a tool that enables comparison of these images over time (perhaps a timeline + ability to select some for side by side viewing) - I'm sure your ideas will be better than mine...

Associated with the above, I assume we'll need new data structures to support this - including aggregating images from a range of sources (ie: we may get nicely arranged images from TREND in an area but there will also others) + allow users to submit a photo of a site rather than a species etc etc...

 Jul 11, 2013 Project Member `#1` leebel...@gmail.com 
Fully agree Peter: 

The current Panoramio application in the SP support site-based images but these are totally unstructured: It is a suite of images taken by anybody at any time and any location. The minimal data is author, image, date/time, latitude and longitude. ANY image uploaded to Panoramio IS available in the SP. There is no search ability in the SP but that would be a terrific idea, if it is possible. All that can be done currently is zoom/pan to area of interest and after clicking the 'Panoramio button' (under zoom slider), images will appear.

In principle, it would be a great idea to have a more systematic approach to site-based images. Mind you, there is nothing stopping anyone from uploading high-quality, systematic site images to Panoramio, e.g., TERN images!

 Cc: moyesyside chris.fl...@gmail.com Labels: -Priority-Low Priority-Medium

**Comment by adam-collins** [comment]
Moved to AtlasOfLivingAustralia/spatial-hub#3
