### ISSUE TITLE
Amend AOO calculation to fixed 0.02 grid - IUCN standard

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#51]
The latest IUCN standard for calculating Area of Occupancy (AOO) recommends that it be calculated ONLY on a 0.02 decimal degree grid (~2x2sq km). The other existing AOO grid resolution options can be removed.

**Comment by Tasilee** [comment]
Is this done yet? Web service is not on api.ala.org.au so unsure.

**Comment by adam-collins** [comment]
Services are available.

**Comment by Tasilee** [comment]
Needs to be in http://api.ala.org.au/
