### ISSUE TITLE
Add Shannon diversity index layer (weekly update?)

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#52]
On the basis of http://data.unep-wcmc.org/datasets/15, and if it is not too much hassle, it would be good to add Shannon's diverity measure (H) to occurrence density, species richness and endemicity layers (at the same spatial resolution). It is easy to calculate - see http://data.unep-wcmc.org/datasets/15. World extent? :| even though it will be spatially biased.

**Comment by adam-collins** [comment]
Test layer on dev. 
id: 2119
short name: sh

**Comment by Tasilee** [comment]
Looks great. Minor edits to sev layers table (still in operation?)

ToProd

**Comment by adam-collins** [comment]
On prod. Will be monthly update to start.
