### ISSUE TITLE
'Invasives' is not picking up all relevant lists

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#53]
@adam-collins: This is a List issue but including it under spatial as it directly affects the area reports.
Checking the area reports against a number of invasives (weeds, pests, etc) it appears that some of the relevant lists are not being picked up - most notably WONS - weeds of national significance. 

This issue relates back to 20/12/2003 where Natasha asked me to designate 'significant' Lists that could/should be used elsewhere in the ALA.  Here were my criteria (cc'd to @pbrenton, John,@djtfmartin ):

1. The List can't easily be created in the ALA system.
2. The list should contain at least 95% name matches against NSL. Having lists that has significant (>5%) unknowns devalues the list. This relates to (3). [I'd reduce this as international lists as lack of matches could be a large proportion. That's another issue].
3. The List owner should accept formal responsibility to maintain the list, with help from recruited editors as needed.
4. The list should not be trivial by containing only a few species? Unsure where you would draw the line here but I think there is one.
5. The list should have practical appeal to a community of interest. Some lists are very insular/one-off while others (e.g., IUCN Redlist) are universally accepted and significant.

Is the List field "Included in BIE" the flag? If so, I'm happy to trawl through and flag the relevant ones.

**Comment by adam-collins** [comment]
Looks to me like the indexed fields pest_flag_s, state_conservation and raw_state_conservation rely on definitions of conservation and pest from sds.ala.org.au.  sds.ala.org.au appears to use lists.ala.org.au when the list is marked as part of SDS, Authoritative, and the other list requirements are met as described at https://github.com/AtlasOfLivingAustralia/sds under 'List Tool Requirements'. WONS, for example, does not appear to have the correct metadata in lists.

After a list is updated for inclusion you should be able to find the data resource id in http://sds.ala.org.au/sensitive-species-data.xml

**Comment by Tasilee** [comment]
We may have a logic problem. Not all invasive species are 'sensitive'. WoNS isn't, as far as I can tell. (WoNS is a national list, not one driven by State/Territory so "pest-flag_s" may not be the best descriptor.)

You are implying that 'invasiveness' is dependent on an entry in the SDS which depends on a List with a subset of characteristics ('authoritative' and 'Part of the SDS')?  If so maybe we need another flag on the Lists that implies "somebody has said that species in this list can be invasive". 

If we want to gather 'invasives' for any reason,  I'd assume that we would either need at least one flag indexed in BIE, OR a flag on the Lists as above (which implies the same thing - but I've no idea which is more efficient).

**Comment by djtfmartin** [comment]
Thanks both.

I think this this is an enhancement to the list tool. So if we add the ability to flag a list as being a list of "invasive" species, and then support a query to retrieve the ids of those lists. We could either enhance the biocache to add the flag or just query from SP to retrieve the list of list IDs.

The SDS isn't actually relevant in this discussion. The role of the SDS is purely to reduce the location information on display for certain species as specified by States and agencies in Australia. A species might we be invasive but without the need to remove/reduce location information.

The pest_flag_s flag was added for the work with APPD, but the lists are not complete. It should be ignored for now.

**Comment by adam-collins** [comment]
For now, added config parameter to include additional columns into species lists. This is driven by 'list collection name' and a set of lists.ala uids

**Comment by adam-collins** [comment]
On sp dev.

**Comment by Tasilee** [comment]
Problem: I created a simple area 

POLYGON((145.33203125001 -35.638494881286,147.1337890625 -35.638494881286,147.1337890625 -34.197210145132,145.33203125001 -34.197210145132,145.33203125001 -35.638494881286))

Area report said 7 species and mapped these to red dots on attached.

Then mapped occurrences of Weeds of National Significance (WONS: DR823) as one 'invasives list' in the same area and there are far more occurrences.

At some point, we will need something in the reports to point back to the lists that each species is on. It would help now also for diagnostics.
![capture](https://cloud.githubusercontent.com/assets/6656350/6661007/2d1f826c-cbf9-11e4-89e8-fcb58ef0e804.jpg)

**Comment by Tasilee** [comment]
![image](https://cloud.githubusercontent.com/assets/6656350/6723475/4b1ef7bc-ce3c-11e4-9491-4bb3cb8f3ff8.png)

**Comment by Tasilee** [comment]
I just checked this for a small area of SW WA and it appears that-

1. The list of species contains a column called "Conservation" when it should be "Invasive" for the invasive lists

2. In examples run, the conservation column contained many blanks (not possible in theory) and potential incorrect lists (WA examples contained NT list). 

3. No invasive list displayed on invasive list

Absence here would be far less harmful than incorrect data.

**Comment by adam-collins** [comment]
is this fixed now?

**Comment by Tasilee** [comment]
yes
