### ISSUE TITLE
Export checklist gives only species with Species rank 

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/spatial-portal#55]
Does the spatial portal export taxonomic lists in different levels through **Export Checklist**? 

Here is the related request asked by an Atlas user:

*I have found a major fault that has crept in since the last time I did a
search in Spatial Portal on organisms in a defined area. All the
infraspecific information (eg subspecies, variety) has been deleted from
the result of the search.*

*Taxonomists regularly move organisms from being a full species to a
subspecies or variety of another species and back again. Governments
gazette particular infraspecies of an organism as Threatened Species or
Noxious Weeds. Other infraspecies of the same species are not so
gazetted. This information is important.*

**Comment by adam-collins** [comment]
Species lists are all rank specific. Need to revisit this in biocache.

**Comment by djtfmartin** [comment]
This issue was moved to AtlasOfLivingAustralia/biocache-service#37
