### ISSUE TITLE
Import KML not working on 8mb file

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#58]
Email from Philippa Wilson (ANU) about World Kopen climate classification layer in KML not importing. The data is at http://people.eng.unimelb.edu.au/mpeel/koppen.html. I downloaded both KMl files and tried the less detailed one and got "Unable to load file. Please try again." Trying again is not appropriate!

We need far better GIS file import functions. This issue is related to #57

**Comment by adam-collins** [comment]
KML files with more than one area won't work. Convert and import a shapefile with multiple areas or a KML with a single area.

Needs better text and error messages.

**Comment by adam-collins** [comment]
Updated text and error messages.
