### ISSUE TITLE
Lists defined in spatial portal should default to private

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/spatial-portal#59]
Lists defined in spatial portal should default to private or we should at least allow a user to specify (checkbox) if the list can be made publicly visible.

@m-r-c could you verify that the webservice for creating the list allows for setting the isPrivate flag and if not raise a issue in specieslist-webapp ?

**Comment by m-r-c** [comment]
The species list service supports setting the isPrivate flag.

**Comment by djtfmartin** [comment]
thanks

**Comment by adam-collins** [comment]
When a user is logged in SP and after creating a list the save prompt has a checkbox defaulting to private.
