### ISSUE TITLE
Tools | Points to grid error

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#61]
Points to Grid failed with the following message: 

Error processing your Sites By Species request. Please try 
again or if problem persists, contact the Administrator.

Please quote the Analysis ID: 1421185948388

**Comment by Tasilee** [comment]
Points to Grid failed with the following message: 

Error processing your Sites By Species request. Please try 
again or if problem persists, contact the Administrator.

Please quote the Analysis ID: 1421186156446

**Comment by adam-collins** [comment]
Config error fixed.
