### ISSUE TITLE
Tools | Scatterplot list fails on selecting GDM output layers

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#63]
Internal Error
The ALA Spatial Portal encountered a serious error. It is recommended to reload the portal but it may be possible to continue. We have recorded the error and will investigate a fix.

GDM worked fine (using William best 5 1960 layers - Eucalyptus - Tasmanian extent). Scatterplot list - selected first of the GDM output (transformed) layers and go the above error with no layer selected. Pressed 'Continue' and tried again with second layer and got same error.

**Comment by adam-collins** [comment]
Fixed on prod.
