### ISSUE TITLE
WKT import is broken

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/spatial-portal#64]
Broken on prod and dev. Just testing with the sample WKT in the description (and others)

![screen shot 2015-01-14 at 9 25 24 pm](https://cloud.githubusercontent.com/assets/444897/5737504/b34dd1ca-9c35-11e4-8a47-97fc0e0bc0b8.png)

**Comment by adam-collins** [comment]
Fixed on prod.

**Comment by djtfmartin** [comment]
that was quick. Cheers
