### ISSUE TITLE
Facets for Datasets and Data Providers list codes instead of names

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/spatial-portal#65]
_From @Tasilee on August 19, 2014 12:13_

*migrated from:* https://code.google.com/p/ala/issues/detail?id=420
*date:* Sun Dec  8 19:58:50 2013
*author:* leebel...@gmail.com
 ---

Previously in the SP, the facet lists used the names of the data providers and datasets. Now it appears that code are used for both in the form of "drxxx" for datasets and "dpxxx" for data providers. 

Rendering them useless without a lookup.

_Copied from original issue: AtlasOfLivingAustralia/biocache-hubs#53_

**Comment by nickdos** [comment]
_From @Tasilee on August 19, 2014 12:13_


*date:* Sun Dec  8 19:59:25 2013
*author:* leebel...@gmail.com
 ---

*(No comment was entered for this change.)*

**Comment by nickdos** [comment]
_From @djtfmartin on August 19, 2014 12:13_


*date:* Sun Dec  8 20:08:08 2013
*author:* moyesyside
 ---

*(No comment was entered for this change.)*

 ---
**UPDATES:**
*Owner:* natasha....@csiro.au
*Status:* Accepted

**Comment by nickdos** [comment]
_From @mbohun on August 19, 2014 12:13_


*date:* Sun Dec  8 20:29:39 2013
*author:* natasha....@csiro.au
 ---

This issue can be resolved temporarily with out code changes. I have configured the SP to ignore the data_resource_uid and data_provider_uid facets.  I have added data_provider and data_resource as custom facets in.

Could you please have a look at the solution on [http://spatial-dev.ala.org.au](http://spatial-dev.ala.org.au) and let me know if this will be OK for the short term?? 

In the future I will make code changes to biocache ws and spatial portal to allow for label substitution of the name.

 ---
**UPDATES:**
*Labels:* -Priority-Critical Priority-Medium Biocache
*Status:* Started

**Comment by nickdos** [comment]
_From @mbohun on August 19, 2014 12:14_


*date:* Sun Dec  8 20:35:23 2013
*author:* natasha....@csiro.au
 ---

NOTES FOR FUTURE FIX:

I think that we need to modify the data_resource_uid and data_provider_uid facets to provide a label and fq value in the JSON. When the label can be used for display purposes and the fq can be used to filter the query.  Similar to how uncertainty works:
[http://biocache.ala.org.au/ws/occurrences/search?q=*:*&facets=data_resource_uid&facets=uncertainty&pageSize=0](http://biocache.ala.org.au/ws/occurrences/search?q=*:*&facets=data_resource_uid&facets=uncertainty&pageSize=0)

**Comment by nickdos** [comment]
_From @Tasilee on August 19, 2014 12:14_


*date:* Sun Dec  8 20:45:09 2013
*author:* leebel...@gmail.com
 ---

We can live with that for now. Works well (as long as note the new location)

PS: Can the other custom categories be meaningfully named? (Prod not dev)?

dr707_act_category
dr707_aus_category
dr707_nsw_category
dr707_nt_category
dr707_qld_category
dr707_sa_category
dr707_tas_category
dr707_vic_category
dr707_wa_category

**Comment by nickdos** [comment]
_From @mbohun on August 19, 2014 12:14_


*date:* Mon Dec 23 17:45:40 2013
*author:* natasha....@csiro.au
 ---

The biocache-service changes from comment `#4` or in dev: 
[http://biocache-test.ala.org.au/ws/occurrences/search?q=*:*&facets=data_resource_uid](http://biocache-test.ala.org.au/ws/occurrences/search?q=*:*&facets=data_resource_uid)

**Comment by nickdos** [comment]
_From @mbohun on August 19, 2014 12:14_


*date:* Wed Apr  2 20:45:17 2014
*author:* natasha....@csiro.au
 ---

Assigning to Adam because this is one of the issues that we discussed while he was in Canberra.

ie Using the biocache-service web services to provide the label and query to use for facets.

Let me know if you need more info Adam.

 ---
**UPDATES:**
*Cc:* -chris.fl...@gmail.com moyesyside
*Labels:* -Type-Defect Type-Enhancement
*Owner:* adam.col...@gmail.com

**Comment by adam-collins** [comment]
Is this resolved now?

**Comment by Tasilee** [comment]
This looks ok now, but on a test using Eucalyptus gunnii, I noted that 1102 of the 1668 records are blank on "data_provider" (SP). Biocache only shows the non-blank records.

**Comment by adam-collins** [comment]
Biocache issue for display of blank records https://github.com/AtlasOfLivingAustralia/biocache-service/issues/72
