### ISSUE TITLE
Multiple SLD body values in environmental envelope - problem with geoserver 2.6.2

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/spatial-portal#68]
Looks like the environmental envelope work is sending 2 sld_body params. 

Example URL:

/geoserver/wms/reflect?layers=ALA:Broadleaved_woodland_landcover_2007_pc_tgt&format=image/png&styles=&sld_body=%3C%3Fxml+version%3D%221.0%22+encoding%3D%22UTF-8%22%3F%3E%3CStyledLayerDescriptor+xmlns%3D%22http%3A%2F%2Fwww.opengis.net%2Fsld%22%3E%3CNamedLayer%3E%3CName%3EALA%3ABroadleaved_woodland_landcover_2007_pc_tgt%3C%2FName%3E%3CUserStyle%3E%3CFeatureTypeStyle%3E%3CRule%3E%3CRasterSymbolizer%3E%3CGeometry%3E%3C%2FGeometry%3E%3CColorMap%3E%3CColorMapEntry+color%3D%220x0000FF%22+opacity%3D%221%22+quantity%3D%2228.18332962490406%22%2F%3E%3CColorMapEntry+color%3D%220x0000FF%22+opacity%3D%220%22+quantity%3D%2228.183332443237305%22%2F%3E%3CColorMapEntry+color%3D%220x0000FF%22+opacity%3D%220%22+quantity%3D%2270.45832824707031%22%2F%3E%3CColorMapEntry+color%3D%220x0000FF%22+opacity%3D%221%22+quantity%3D%2270.45833529290314%22%2F%3E%3C%2FColorMap%3E%3C%2FRasterSymbolizer%3E%3C%2FRule%3E%3C%2FFeatureTypeStyle%3E%3C%2FUserStyle%3E%3C%2FNamedLayer%3E%3C%2FStyledLayerDescriptor%3E&sld_body=%3C%3Fxml+version%3D%221.0%22+encoding%3D%22UTF-8%22%3F%3E%3CStyledLayerDescriptor+version%3D%221.0.0%22+xmlns%3D%22http%3A%2F%2Fwww.opengis.net%2Fsld%22%3E%3CNamedLayer%3E%3CName%3EALA%3ABroadleaved_woodland_landcover_2007_pc_tgt%3C%2FName%3E%3CUserStyle%3E%3CFeatureTypeStyle%3E%3CRule%3E%3CTitle%3EPolygon%3C%2FTitle%3E%3CPolygonSymbolizer%3E%3CFill%3E%3CCssParameter+name%3D%22fill%22%3E%23000000%3C%2FCssParameter%3E%3C%2FFill%3E%3C%2FPolygonSymbolizer%3E%3C%2FRule%3E%3C%2FFeatureTypeStyle%3E%3C%2FUserStyle%3E%3C%2FNamedLayer%3E%3C%2FStyledLayerDescriptor%3E&SRS=EPSG%3A3857&TRANSPARENT=TRUE&VERSION=1.1.0&SERVICE=WMS&REQUEST=GetMap&BBOX=939258.5434375,6887893.831875,1252344.61125,7200979.8996875&WIDTH=256&HEIGHT=256

URL decoded the passed SLD's are:

<?xml version="1.0" encoding="UTF-8"?><StyledLayerDescriptor xmlns="http://www.opengis.net/sld"><NamedLayer><Name>ALA:Broadleaved_woodland_landcover_2007_pc_tgt</Name><UserStyle><FeatureTypeStyle><Rule><RasterSymbolizer><Geometry></Geometry><ColorMap><ColorMapEntry color="0x0000FF" opacity="1" quantity="28.18332962490406"/><ColorMapEntry color="0x0000FF" opacity="0" quantity="28.183332443237305"/><ColorMapEntry color="0x0000FF" opacity="0" quantity="70.45832824707031"/><ColorMapEntry color="0x0000FF" opacity="1" quantity="70.45833529290314"/></ColorMap></RasterSymbolizer></Rule></FeatureTypeStyle></UserStyle></NamedLayer></StyledLayerDescriptor>

and

<?xml version="1.0" encoding="UTF-8"?><StyledLayerDescriptor version="1.0.0" xmlns="http://www.opengis.net/sld"><NamedLayer><Name>ALA:Broadleaved_woodland_landcover_2007_pc_tgt</Name><UserStyle><FeatureTypeStyle><Rule><Title>Polygon</Title><PolygonSymbolizer><Fill><CssParameter name="fill">#000000</CssParameter></Fill></PolygonSymbolizer></Rule></FeatureTypeStyle></UserStyle></NamedLayer></StyledLayerDescriptor>

**Comment by adam-collins** [comment]
fixed
