### ISSUE TITLE
Pipeline for background compute-intensive tasks

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/spatial-portal#7]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=82
*date:* Thu Aug  8 05:42:39 2013
*author:* moyesyside
 ---

Original Issue  - [https://code.google.com/p/alageospatialportal/issues/detail?id=1075](https://code.google.com/p/alageospatialportal/issues/detail?id=1075)

Project Member Reported by leebel...@gmail.com, Jul 11, 2013 
While users can send compute intensive tasks to background processing, there is no management of the number and intensity of tasks. It is highly likely (and desirable) that the number of 'hard' tasks increase over time. These can be ALA tasks (e.g., processing layers) or user-tasks. 

It would therefore be wise to setup a way to shuffle such tasks off to a pipeline that could schedule and manage compute-intensive tasks and notify authors when complete. In this way, we could better manage impact on servers. Obviously a separate server for the pipeline would be neat.

**Comment by adam-collins** [comment]
This is resolved in spatial-service
