### ISSUE TITLE
Replace links to BioStor with JournalMap

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#70]
The recent development of https://www.journalmap.org/search takes data from BioStor and has a useful API - https://www.journalmap.org/developer/documentation/1-0

This central repository accepts a wide range of automated and manual feeds, and is an ideal resource for those ALA users who would find it very useful to know of biodiversity-related publications within user-defined areas.

The OzTrack bibliography is now included BTW!

**Comment by Tasilee** [comment]
When implemented, add reference in PDF area report to https://www.journalmap.org/

**Comment by adam-collins** [comment]
On dev. Biostor not yet removed.

**Comment by Tasilee** [comment]
This works very well! I know that Biostor -> JournalMap and on the checked area, this was true. Remove Biostor at your convenience from the standard area report.
