### ISSUE TITLE
Update PDF Area Report summary page and content

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#71]
Partly dependent on #70, update summary of area report as per image and add list of JournalMap refs to report and TOC.
![capture_2](https://cloud.githubusercontent.com/assets/6656350/6055543/a32f409a-ad55-11e4-9767-8a015d7f3e2d.jpg)

**Comment by Tasilee** [comment]
Also, could this link to be added to the general references at the end of the report? It is a beauty-

http://lntreasures.com/australia.html        - Lists of Australian endemic species

**Comment by adam-collins** [comment]
On dev.

**Comment by Tasilee** [comment]
Nice
