### ISSUE TITLE
Add Extent of Occurrence (EOO) values to taxa

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#72]
Adding this here given there is a related issue #51

Extent of Occurrence (EOO) is one of the standard IUCN criteria for identifying "Critically Endangered, Endangered and Vulnerable taxa" - http://www.iucnredlist.org/static/categories_criteria_2_3

This statistic is the AREA (sqkm) of the minimum convex hull of the occurrences for a taxa and is complementary to the Area of Occupancy (AOO: #51). AOO and EOO are extremely useful for evaluating the status of taxa.

EOO (and AOO) would need to be updated as new occurrence records are added. Weekly update?

BOTH these measures should be reported on the BIE species overview page (profile).

Ideally, a web service that accepts a name and returns EOO and AOO (at 0.02) would be ideal.

**Comment by Tasilee** [comment]
Fabulous! Minor-

1. Use "Calculate AOO and EOO" for the Tool title as if users don't know what they are...don't use.
2. Result window: Need to be able to download the result, txt / html fine.

3. Optional - can the 0.02 grid points for AOO easily be mapped as a layer?

**Comment by adam-collins** [comment]
Is this done?

**Comment by Tasilee** [comment]
yes
