### ISSUE TITLE
Add Import | Contextual layer

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#73]
Users (and myself) often incorrectly attempt to import a shapefile or kml file (a 'layer') under "Import | Areas". A contextual layer can be imported under "Import | Areas" ONLY to define a new area from one or more user-selected polygons (as one new 'area').

To complement the WMS function, it would therefore be extremely useful to be able to import a contextual layer as a new layer (not area): Import | Contextual layer.

**Comment by adam-collins** [comment]
Moved to AtlasOfLivingAustralia/spatial-hub#6
