### ISSUE TITLE
Enable use of all available attributes associated with polygons in contextual layers

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#74]
Take the CAPAD layer. Currently we (at least)

1. Create a map legend based on the classification (reserve type - e.g., national parks)
2. Enable a gazetteer search of the individual polygon names (e.g., Royal NP)
3. Display the polygon class in the hover tool
4. Cross tabulate based on layer classification
5. Sample based on polygon class

It would be useful at least with (3) and (5) to be able to display all values relating to a polygon, for example its classification (class: e.g., National Park) and its name (e.g., The Royal National Park). With some layers, there may be a multi-level (hierarchical?) classification - each polygon may have multiple associated values, one of which is area.

Area is a particularly useful polygon attribute. For example, to determine how 'secure' one or more species are across a reserve network, we need to know the occurrence of species in the network and the size of the reserves.

**Comment by adam-collins** [comment]
Moved to AtlasOfLivingAustralia/spatial-hub#5
