### ISSUE TITLE
Site environmental layer value comparison

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/spatial-portal#75]
Histograms or something nice.

**Comment by Tasilee** [comment]
Too cryptic. Context?

**Comment by adam-collins** [comment]
Idea for dev
1. Upload sites with Import | Points. 
2. Tools | Sites Report. Along the lines of Area Report for sites comparisons. Similar to #30 with a focus on layers instead of species.

**Comment by Tasilee** [comment]
The most useful form of this type of data (sampling layers at points) is a CSV so the data can be analyzed as required. One simple (analysis, not necessarily programming!) on-screen possibility is to use a histogram (one layer at a time) or scatterplot - list (multiple layers) as long as there are not too many layers requested.

The #30 connection is only if points had multiple species observations and the goal was the generation of a species x sites matrix.

**Comment by adam-collins** [comment]
On SP dev, Tools | Point Comparisons

**Comment by Tasilee** [comment]
Nice option. Suggest

1. Add to Map | Points
2. Text for (step 2): Add points by clicking on the map [Users better to Import | points rather than manual]
3. Text for (step 3): Click on Sample button to sample all layers at points

Edit doesn't seem to remove original point.

**Comment by Tasilee** [comment]
This appears to be working fine.
