### ISSUE TITLE
Tabulation of lifeform or species list between two areas

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#76]
Currently, it is difficult to use the SP to evaluate for example how well a species, a species list or lifeform are 'conserved'. This is indicative of a basic and extremely important function.

To address this, we need a way of tabulating species across a single contextual layer. In its simplest form -

(Assume Australian extent)			
Input:			
Lifeform/List	        X		
Contextual Layer	Y		
Output - a table:			
  	                                       IN	OUT    TOTAL
Occurrences (of lifeform/list)	a	  b	       c
Richness (lifeform/list)	        d	  e	     n/a
Area sqkm(contextual layer)   	f	  g           h

The key function that doesn't currently exist is areas in sqkm in/out.

Occurrences in/out can be easily determined from sampling the layer. This also gives access to the different classes on each layer (if there are multiple classes).

Species richness could also be tabulated now via sampling.

**Comment by Tasilee** [comment]
After discussion with Adam, I realize that the 'hard part' of this option is best seen as another Area creation option that should be in Add to Map | Area. Basically, ANY two areas form one dimension of this task (call them A and B). The other dimension is the species list/group - which should not include in this case 'All species' (at this stage?) because of bias and computational limits. Users have to explicitly state which set of species are of interest via lifeform facet or List.

Two areas are needed and in the simplest case, two areas could be created by any of the Add to Map | Area options. The one situation that is not already covered is the creation of an area by effectively using all polygons in a contextual layer such as CAPAD 2012 terrestrial. One new area layer would be created that combined all classes/areas of the CAPAD layer. In this example, the A layer would be this combined CAPAD and the B layer would be its spatial complement (any area in Australia that didn't have a CAPAD terrestrial polygon. Other layers could be for example like DIWA where there was only DIWA class (at that high-level of classification - not at the level of the NAME of individual DIWA areas). 

The contextual layers that are possible candidates for this tool would have the property of Not having 100% spatial coverage as this would mean there is no - Non A areas. Examples would include Australia States/Territories, LGAs, IBRA or NRM regions. That said, a user could create an area from one or more of those layer's polygons.

In theory, users could create an area external to Australia, but the data bias would mitigate against such use in this tool.

Nothing stopping A and B being marine, but any overlap with terrestrial would produce a potential area size bias.

**Comment by adam-collins** [comment]
For the DIWA non-name grouping example above, a new layers db fields table entry and reindexing will be required.

**Comment by Tasilee** [comment]
The dev version looks good. The tabulation is exactly what is needed. Terrestrial options seem good but the marine option (say using CAPAD 2014 Marine states it is using the rest of the world when I think it should use IMCRA 4 (which it may be using but not displaying properly?).

Noting my comment on 16th of November above, I do think that the ability of effectively using an Add to Map | Area | Merge contextual polygons is a more general way to go. The input then into the in/out function would be any two areas. As I am unsure what processing is being done prior to the in/out function, I don't know how viable the general two-area approach would be.

**Comment by Tasilee** [comment]
In the general case (compare Area A with Area B), this devolves to a better name "Compare areas". While it is possible to use Area reports to compare species in two areas, it would be very neat at some point to generate a two-by-two table from this option with clickable links on values that listed the relevant species, namely-

                                Area B
                          Yes            No
              Yes        W              X
Area A
               No         Y              Z

The other parts of the current table (area, occurrences) don't require elaboration.

**Comment by Tasilee** [comment]
That table didn't come out well, so here is a summary of what seems minimalist for a comparison of two areas (say A and B)-

- Area of A
- Area of B
- Species in A (species list - only if not >~X) where X ~ 2000? link
- Species in B (species list - only if not >~X) link
- Species common to A and B (species list - only if not >~X) link
- Species in A not in B (species list - only if not >~X) link
- Species in B not in A (species list - only if not >~X) link

- Number of occurrence records in A (link to set)
- Number of occurrence records in B (link to set)
- Number of occurrence records in A and B (link to set)
- Number of occurrence records in A and not B (link to set)
- Number of occurrence records in B and not A (link to set)

i.e. Venn diagram where we can't just assume an overlap of A and B

**Comment by Tasilee** [comment]
After discussion, I think the useful stats can be limited to (considering two areas defined as A and B - that may or may not be overlapping geographically)

Area of A in sqkm
Area of B in sqkm
Species common to both A and B
Species in A but not in B 
Species in B but not in A

**Comment by adam-collins** [comment]
on prod

**Comment by Tasilee** [comment]
Fabulous!! Nicely done.
