### ISSUE TITLE
Allow a URL to open the phylogenetic diversity tool and set default parameters

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/spatial-portal#78]
Adding URL parameters
tool, tool to open (phylogeneticdiversity)
toolParameters (optional), JSON object with optional "selectedAreas" (comma delimited layer names) and optional "selectedTrees" (comma delimited tree ids)

Tool will open and allow confirmation of changes to preset settings.

Example: add area "Canberra", pid 5723205 (dev), open phylogenetic diversity tool and select this new area and tree2857.
http://spatial-dev.ala.org.au/?tool=phylogeneticdiversity&pid=5723205&toolParameters={%20%22selectedAreas%22:%22Canberra%22%20,%20%22selectedTrees%22:%22tree2857%22}

Phylo service is changing. SP phylogenetic diversity tool is not currently working.

**Comment by adam-collins** [comment]
SP phylogenetic diversity tool is updated.

**Comment by djtfmartin** [comment]
Thats cool
