### ISSUE TITLE
"Botanical Districts of Australia" layer

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/spatial-portal#79]
Original issue: https://code.google.com/p/ala/issues/detail?id=66

Description: https://www.anbg.gov.au/cpbr/anhsir/anhsir-manual/botanical-districts.html

We got a request for this layer (raw file) from Anna Monroe. Long story short: Nunzio Knerr (nunzio.knerr@csiro.au) may have this data but he's currently on leave.

**Comment by Tasilee** [comment]
This is a superset of Beard's Provinces for WA. I'll move this over to https://github.com/AtlasOfLivingAustralia/layers-service and approach Jim Croft about the data.
