### ISSUE TITLE
Pre-existing List selection fails

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#80]
If I search for a term that may be in a pre-existing list, and nothing is found, you can't reset the search and try again. 

There is also a problem in paging through a list (see image). Something's bung.

![capture](https://cloud.githubusercontent.com/assets/6656350/6569248/cdcc786e-c73a-11e4-9b54-6e2e730703af.jpg)

**Comment by adam-collins** [comment]
Fix is on dev.
