### ISSUE TITLE
GDM Failure

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#81]
Requesting a GDM run on List Australian Bat Species (82 species: Lee Belbin), Australian extent, best 5 KW layers produces error:
![capture_2](https://cloud.githubusercontent.com/assets/6656350/6569810/b258c07e-c744-11e4-952e-be3c5e5b7e29.jpg)

Apparently this fail was due to biocache timeouts, but I'm figuring there are other issues given user feedback.

We have had a number of requests to support Australian spatial extent and lifeform-level runs. If possible, we need to either be able to support such requests, or pull GDM. Possibly no easy ask given GDM is probably the most compute and memory intensive tool we have in the SP.

**Comment by Tasilee** [comment]
Suggested realistic test case is all Eucalyptus (genus), Australian extent, best 5 layers (any), defaults

**Comment by adam-collins** [comment]
Fix on dev.

**Comment by Tasilee** [comment]
I get 'Unknown error' using Australian window extent, Acacia (or Eucalyptus), best 5. I don't get passed the first phase.

**Comment by adam-collins** [comment]
Issue is still a timeout in SP and the occasional timeout fetching the occurrences for GDM step 1. Not the nicest fix implemented but it seems to work. Added red text 'in progress...' and disabled the 'next' button.

Both Acacia and Eucalyptus take about 10min for step 1 and 2min for step 2. Both have around 550000 occurrences. This is using best 5 and Australian extent on dev.

**Comment by Tasilee** [comment]
Nice work Adam! I re-tested it on Acacia scenario and also dr2171 and it looks good.

**Comment by Tasilee** [comment]
Just noticed a few minor issues with the output files

1. Input "Assemblage: " is blank - should contain species list
2. Last four graph/images maxti.png, minti.png, radnx.png and rainx.png missing/broken links. Why 4 when best 5? Look slike it may have been hard wired!? These graphs (and more!) for the layers are in the graphs sub folder of the output and should have been

2030A1BMk35M_evapi.png
2030A1BMk35M_evapi_thumb.png
2030A1BMk35M_pwat_max.png
2030A1BMk35M_pwat_max_thumb.png
2030A1BMk35M_raini.png
2030A1BMk35M_raini_thumb.png
2030A1BMk35M_srain2.png
2030A1BMk35M_srain2_thumb.png
2030A1BMk35M_srain2mp.png
2030A1BMk35M_srain2mp_thumb.png

These aren't current used in the report.

**Comment by adam-collins** [comment]
Fixed on prod

**Comment by Tasilee** [comment]
Tested on Euc + Best 5 scenario: Awesome!
