### ISSUE TITLE
dev: Add to Map | Merge areas not working as expected

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#84]
I created an 'area' from the environmental envelope option (a few small polygons), then another area via WKT, then attempted to merge them, but the selection box only had the latter  area as an option. See attached. 
![capture_2](https://cloud.githubusercontent.com/assets/6656350/6590202/cda8a27e-c800-11e4-949b-e08c3076c59b.jpg)

**Comment by adam-collins** [comment]
Will update to note that environmental envelopes are excluded.

**Comment by adam-collins** [comment]
Updated text is on dev.

**Comment by Tasilee** [comment]
OK. (Was a tall order).
