### ISSUE TITLE
dev: Point to grid fails

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#88]
Tasmania window extent, Eucalyptus gunnii, generate all outputs. Fails with attached (at least we got a helpful message this time)
![capture](https://cloud.githubusercontent.com/assets/6656350/6590778/69d3fe38-c80a-11e4-9273-907cabc500c6.jpg)

**Comment by adam-collins** [comment]
Fixed on dev.

Need to fix output csv not removing zero rows.

**Comment by Tasilee** [comment]
Tests OK.
