### ISSUE TITLE
dev: Classification fails

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#89]
Tasmanian window extent, Best 5 2030 layers, 50 groups. Blank zip produced and "Layer unavailable".
![capture](https://cloud.githubusercontent.com/assets/6656350/6590804/08d2dc3e-c80b-11e4-941e-dce2af6f5c02.jpg)

**Comment by adam-collins** [comment]
Analysis config and progress box fixed on dev.

**Comment by Tasilee** [comment]
Problem remains. Same map and classification.log (only file in zip) contains "start ALOC"

**Comment by adam-collins** [comment]
I made a new problem when fixing points to grid. File permissions.

Working again.

**Comment by Tasilee** [comment]
Nice.
