### ISSUE TITLE
dev: Prediction fails immediately

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#90]
![capture_2](https://cloud.githubusercontent.com/assets/6656350/6590824/62113f66-c80b-11e4-8530-2a4c9d068dec.jpg)

**Comment by adam-collins** [comment]
Fixed dialog and analysis problem. Working again.

**Comment by Tasilee** [comment]
We get further, but end in failure. E.gunnii | Tasmanian extent | Best 5 2030 + IBRA 7 subregions | Jackknife | 5% training produces-

![capture_2](https://cloud.githubusercontent.com/assets/6656350/6610155/4e93ad4e-c8af-11e4-8174-1bf80fe88699.jpg)

**Comment by adam-collins** [comment]
Failed on IBRA 7 subregions. Not all new layers are indexed for analysis.  Kicked it off.

**Comment by Tasilee** [comment]
IBRA 7 isn't new though? Just not indexed. Triggers a question on full processing of the newer layers. 

Prediction with IBRA 6 subregions - dandy.
