### ISSUE TITLE
dev: Facet on import points field crashes

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#91]
The file imported fine, points mapped, facets shown on legend, select the first (which has worked on prod) and get error as in attached. Legend gets stuffed.
![capture_3](https://cloud.githubusercontent.com/assets/6656350/6590903/53e38cf4-c80c-11e4-85fa-0d54b41c89b2.jpg)

**Comment by adam-collins** [comment]
Fixed config i18nURL on dev.

**Comment by Tasilee** [comment]
checks out ok.
