### ISSUE TITLE
dev: Export map - screen capture is far better

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#93]
The jpg, png and pdf options for Export map seem far worse than a simple screen capture. 
![map_export](https://cloud.githubusercontent.com/assets/6656350/6590997/c6ab0a18-c80d-11e4-8580-eb69108a991b.jpg)
vs
![capture_2](https://cloud.githubusercontent.com/assets/6656350/6590999/cd7786dc-c80d-11e4-960b-f81dcc9f44e7.jpg)

**Comment by adam-collins** [comment]
This is a limitation of using the Google basemap.
