### ISSUE TITLE
Calculate AOO and EOO for a given set of records

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#94]
Generating overall lowest-level taxa AOO and EOO as summary statistics is a hint to scientists that these values are available, but as a more generic solution, we need to be able to calculate (on the fly) AOO and EOO for a set of selected records as defined at least by a point layer in the SP. 

Reason: Most record sets for a taxa will contain odd records that will bias the stats. Users will therefore need to be able to either filter ALA records or provide their own. In retrospect, it seems wise to offer a web service that basically accepts points (lat-lon) and produces AOO and EOO. No other parameters are needed.

**Comment by adam-collins** [comment]
Something on dev in Tools | AOO and EOO. Inputs are an area and a species. Output are the 2 numbers and the convex hull added as an area layers.

To speed it up, not that it needs it, the convex hull is created from the 0.02 degree grid coordinates, unless there are not enough unique coordinates. 0.01, 0.001, and 0.0001 coordinates are attempted until enough unique coordinates are found. Is this OK, or should starting with 0.0001 coordinates or the actual coordinates be used?

**Comment by Tasilee** [comment]
Fabulous! EOO should be calculated from actual coordinates if at all possible and layer should be called "Extent of occurrence: taxa name".

**Comment by Tasilee** [comment]
AOO is fixed at 0.02 degree grid BTW.

**Comment by Tasilee** [comment]
Ah, and placement of Tools option directly after "Detailed area report" as this is the closest link

**Comment by adam-collins** [comment]
Update on dev.

**Comment by adam-collins** [comment]
Is this ready for prod?

**Comment by Tasilee** [comment]
Yes

From the Pad
