### ISSUE TITLE
dev: Add to Map | Species | Use existing list - List problem?

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#96]
Selected my bat list and got the error below. Certainly not 20 million occurrences!!
![capture](https://cloud.githubusercontent.com/assets/6656350/6609134/1d8a9198-c8a2-11e4-9f85-b54c58cf97be.jpg)

If I use the lists.ala.org.au and select the bat list and View in Spatial Portal, I think I get ALL occurrences! Something seriously wrong with lists...

**Comment by adam-collins** [comment]
Some recent changes cause it ignore the entire list when there was a species list item without an lsid.

**Comment by adam-collins** [comment]
Fix on dev.

**Comment by Tasilee** [comment]
Yep
