### ISSUE TITLE
"Loading" remains on map after species mapped

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#97]
![capture_3](https://cloud.githubusercontent.com/assets/6656350/7464094/e7701340-f302-11e4-8c26-ed481807110a.jpg)

Also, occurrences of "Layer unavailable" noted when at particular zoom level - as in image.

**Comment by adam-collins** [comment]
Trying something new. No idea if it will help.

**Comment by Tasilee** [comment]
No problems on various testing so looking good. ToProd

**Comment by adam-collins** [comment]
on prod. If it turns up again we can move the loading box somewhere out of the way.
