### ISSUE TITLE
Safari browser (Mac) problem on select boxes

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#98]
Reported by Nola Handcock (Macquarie University) on Mac using Safari. Tested on SP, Add to Map | Areas | Gazetteer polygon | New South Wales (any of). Once the layer is selected, the NEXT button is not highlighted/selectable. Tested on various selections. Works ok with Firefox on same Mac.

**Comment by adam-collins** [comment]
I could not reproduce this one. 

There were user generated objects that are now removed from the list. 

I do not think it was the case here but sometimes a combobox will not register the selection. The workaround is to click the down arrow to open the list, select another item, click the down arrow to open the list again and select the required item.

**Comment by adam-collins** [comment]
Still cannot reproduce.
