### ISSUE TITLE
Add units to scatterplot axes

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-portal#99]
User requested to know what the units were of environmental values forming the axes of the scatterplots (Tools | Scatterplots and Tools | Scatterplot List). In many cases, the units of the scales are not obvious.
![capture](https://cloud.githubusercontent.com/assets/6656350/7692015/cf3b4ea6-fe02-11e4-982e-4495bead785a.jpg)

**Comment by adam-collins** [comment]
on dev

**Comment by Tasilee** [comment]
Close but all axes tested have "degrees C/day" :|

**Comment by adam-collins** [comment]
On prod.

**Comment by Tasilee** [comment]
Tested great. Nice work
